import {Column} from 'react-table';

function getValues(obj: object, keys: string[]): string[] {
  return keys.map(key => JSON.stringify((obj as any)[key]));
}

// FIXME can't get the value generated by `accessor` directly?
// have to use `row.values` and `columnIds` to get
export const columnFilter: Column<any>['filter'] = (rows, columnIds, filterValue) => {
  return rows.filter(row => {
    let values = getValues(row.values, columnIds);
    return values.some(it => it.includes(filterValue));
  })
}
